name: LLVM Tests

on:
  push:
    branches:
      - 'release_*x'
    paths:
      - 'llvm/**'
      - '.github/workflows/llvm-tests.yml'
  pull_request:
    branches:
      - 'release_*x'
    paths:
      - 'llvm/**'
      - '.github/workflows/llvm-tests.yml'

jobs:
  build_llvm:
    name: llvm check-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
    - name: Setup Windows
      if: startsWith(matrix.os, 'windows')
      uses: llvm/actions/setup-windows@main
      with:
        arch: amd64
    - name: Free disk space (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
    - name: Install Ninja
      uses: llvm/actions/install-ninja@main
    - uses: actions/checkout@v1
      with:
        fetch-depth: 250
    - name: Test llvm macOS
      if: ${{ matrix.os == 'macOS-latest'}}
      run: |
        nproc="sysctl -n hw.logicalcpu"
        ./build-llvm-project.sh -t X86 -d RelWithDebInfo -e "clang" -p /usr/local -s -n `$nproc` -i -v
        cd build
        make check-all
    - name: Test llvm ubuntu
      if: ${{ matrix.os == 'ubuntu-latest'}}
      run: |
        ./build-llvm-project.sh -t X86 -d RelWithDebInfo -p /usr/local -s -n $(nproc) -i -v
        cd build
        make check-all
